### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by XxttCrystal** [HungTeen/HTOpenTD#1]
1.对于kjs事件的支持(再议，不急)
2.对于新的选项：
      移动选项:
	类似骷髅的移动方式(近距离远距离结合，近距离逃跑远距离进攻)
	类似末影人的移动方式（瞬间定点移动）
	一般的移动方式（贴脸就对了）
	固定移动方式（固定的周期每次向前或者向后，或者瞬间改变坐标到自己位置的多少偏移位置）
推荐原因：移动炮台的制作，更加大型的防御战斗可能需要类似的内容
3.对于新的选项：
	吸引选项：[想法来源：磁力菇]
		可以吸引实体到一个点或者吸引实体的装备到目标位置，然后触发下列选项事件：
		1.如果吸引实体：(可以多选，实现时候从上至下执行)
			a.击杀该实体
			b.移动该实体到某偏移位置
			c.改变实体的nbt
			d.修改实体某个身体位置的装备
			e.给实体附着buff
			f.在某个位置生成一个实体
			g.等待时间
		2.如果吸引实体的装备：（多选，同上）
			a.把这个装备返回
			b.给这个装备改变nbt（覆盖其nbt或者重置修改nbt两种选项）
			c.销毁这个装备
			e.等待时间
			f.在某个位置生成一个实体
推荐愿意：可以辅助玩家战斗，可以增益队友实体，做的就像修理台或者移动医生一样

**Comment by HungTeen** [comment]
1. 等玩法完整再说。
2. 会考虑，但优先级不高。
3. 可能有吸引选项，但不会和HTPVZ做的一样细节丰富。

**Comment by HungTeen** [comment]
基本完成
