### ISSUE TITLE
对Kubejs支持的详细解释

### ISSUE THREAD

**Issue by XxttCrystal** [HungTeen/HTOpenTD#10]
以下名称都为暂定

1. **preSummonTower独有**

isCanPost() 可否在该处放置 返回值为bool
setCanPost() 设置是否可以放置 void
getLimitType() 获取放置要求种类 String
getExperienceLimits() 获取经验限制NBT组 ComponentTag 如果没有这个限制返回null
    每一个限制中NBT组内含有的Key: xp level cost_xp cost_level
setExperienceLimit() 设置经验放置限制 传入ComponentTag或String
getBlockLimits() 返回方块限制组 ComponentTag 如果没有这个限制返回null
    每一个限制中NBT组内含有的Key: state tag blocks
setBlockLimit() 设置方块放置限制 传入ComponentTag或String
setLimitTip() 设置不能放置时的提示(包含方块，实体，周围实体三种)
getEntityLimits() 获取实体限制组 ComponentTag 如果没有这个限制返回null
    每一个限制中NBT组内含有的Key: filter(以ComponentTag形式存在)
setBlockLimit() 设置实体放置限制 传入ComponentTag或String
getAroundEntityLimits() 获取实体放置限制 ComponentTag 如果没有这个限制返回null
    每一个限制中NBT组内含有的Key: width height min_count max_count filter(以ComponentTag形式存在)
getInventoryLimits() 获取物品限制组 ComponentTag 如果没有这个限制返回null
    每一个限制中NBT组内含有的Key: own_items consume_items

2. **防御塔设置**
addTargetSetting() 增加一个索敌器 传入ComponentTag或String
addConstantSetting() 增加一个持续作用组件 ComponentTag或String
getTargetSettings() 获取锁敌器列表 每一项目都称为"锁敌设置对象"
锁敌设置对象(OTDTargetSettings)的方法：
- get/setPriority() 获取或者设置权重
- get/setChance() 获取或者设置每tick的搜索频率
- is/setClosest() 获取或者设置是否选取最近目标
- get/setRefreshCd() 获取或者设置找到目标后，多久更新一次
- getTargetFinder() 获取锁敌器 返回"锁敌器对象"
- setTargetFiner() 设置锁敌器 传入ComponentTag或String或者一个锁敌器对象
锁敌器对象(OTDTargetFinder)的方法
- get/setType() 获取或者设置索敌方法，传入或输出直线索敌对象或者范围索敌对象
- 直线索敌对象(OTDLineTargetFinder)方法
- - get/setHorizontalDegree() 获取或者设置水平面逆时针偏移角度
- - get/setVerticalDegree() 获取或者设置垂直面向上偏移角度
- - get/setLength() 获取或者设置直线搜索长度
- - get/setTargetFilter() 获取或者设置目标过滤器 传入ComponentTag或String或者一个过滤器对象，输出一个过滤器对象
- 范围索敌对象(OTDRangeTargetFinder)方法
- - is/setCheckSight() 获取或者设置是否需要视野
- - get/setWigth() 获取或者设置索敌宽度
- - get/setHeight() 获取或者设置索敌高度
- - get/setTargetFilter() 获取或者设置目标过滤器 传入ComponentTag或String或者一个过滤器对象，输出一个过滤器对象
过滤器对象(OTDTargetFilter)方法
实在写不动了，写法和上面一样，一级输出对象输入ComponentTag
作用组件也是类似，要可以设置可以获取

**Comment by HungTeen** [comment]
完成
