### ISSUE TITLE
Kubejs的支持更新

### ISSUE THREAD

**Issue by XxttCrystal** [HungTeen/HTOpenTD#8]
允许get或set某个炮台或者子弹的属性，比如速度，伤害等等
允许实时更新贴图
允许调用动画（做到攻击动画等等的效果）（只需要传入一个动画名参数即可，找不到会不播放，需要在制作动画的时候做好并命名）
允许更新模型
允许用KubeJS或者效果组件更新贴图和模型
可选添加死亡动画，默认无

寻路方式增加近战寻路（目前寻路会绕圈行动）

**Comment by HungTeen** [comment]
完成
